// Generates src/prediction/bigrams.generated.ts from Peter Norvig's word and
// bigram counts (https://norvig.com/ngrams/), which are derived from the
// Google Web Trillion Word Corpus. Run with: pnpm data:bigrams
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const UNIGRAMS_URL = "https://norvig.com/ngrams/count_1w.txt";
const BIGRAMS_URL = "https://norvig.com/ngrams/count_2w.txt";

// how many of the most frequent words are considered real vocabulary
const VOCAB_SIZE = 6000;
// how many next-word suggestions to keep per context word
const NEXT_PER_WORD = 32;
// how many of the most frequent words to emit as the fallback suggestion list
const COMMON_SIZE = 250;

// the corpus is web text; filter out webisms, abbreviations, apostrophe-less
// contractions (the curated data has the real ones), and words that make poor
// spoken suggestions
const BLOCKLIST = new Set([
    "arent",
    "cant",
    "couldnt",
    "didnt",
    "doesnt",
    "dont",
    "hasnt",
    "havent",
    "hes",
    "isnt",
    "ive",
    "im",
    "lets",
    "shes",
    "thats",
    "theres",
    "theyre",
    "wasnt",
    "weve",
    "whats",
    "wont",
    "wouldnt",
    "youll",
    "youre",
    "youve",
    "aug",
    "apr",
    "com",
    "css",
    "dec",
    "dvd",
    "edu",
    "etc",
    "faq",
    "feb",
    "ftp",
    "gov",
    "htm",
    "html",
    "http",
    "https",
    "inc",
    "jan",
    "jul",
    "jun",
    "los",
    "ltd",
    "mar",
    "mon",
    "net",
    "nov",
    "oct",
    "org",
    "pdf",
    "php",
    "sep",
    "thu",
    "tue",
    "url",
    "usr",
    "wed",
    "www",
    "xml",
]);

function isWord(word) {
    if (!/^[a-z]+$/.test(word)) {
        return false;
    }
    if (word.length === 1 && word !== "a" && word !== "i") {
        return false;
    }
    return !BLOCKLIST.has(word);
}

async function fetchLines(url) {
    console.warn(`downloading ${url}...`);
    const response = await fetch(url);
    if (!response.ok) {
        throw new Error(`${url} responded ${response.status}`);
    }
    const text = await response.text();
    return text.split("\n");
}

const unigramLines = await fetchLines(UNIGRAMS_URL);
const vocab = new Set();
for (const line of unigramLines) {
    const [word] = line.split("\t");
    if (word != null && isWord(word)) {
        vocab.add(word);
        if (vocab.size >= VOCAB_SIZE) {
            break;
        }
    }
}
console.warn(`vocabulary: ${vocab.size} words`);

const bigramLines = await fetchLines(BIGRAMS_URL);
const nextWords = new Map();
let kept = 0;
for (const line of bigramLines) {
    const [pair, countText] = line.split("\t");
    if (pair == null || countText == null) {
        continue;
    }
    const [first, second] = pair.split(" ");
    if (
        first === second ||
        first == null ||
        second == null ||
        !vocab.has(first) ||
        !vocab.has(second)
    ) {
        continue;
    }
    let entries = nextWords.get(first);
    if (entries == null) {
        entries = [];
        nextWords.set(first, entries);
    }
    entries.push([second, Number(countText)]);
    kept++;
}
console.warn(`kept ${kept} bigrams for ${nextWords.size} context words`);

// "i" is always written "I"; the corpus is all lower case
const display = (word) => (word === "i" ? "I" : word);

const entries = [...nextWords.entries()]
    .sort(([a], [b]) => (a < b ? -1 : 1))
    .map(([word, pairs]) => {
        const top = pairs
            .sort(([, a], [, b]) => b - a)
            .slice(0, NEXT_PER_WORD)
            .map(([next]) => display(next));
        return `    ${JSON.stringify(word)}: ${JSON.stringify(top)},`;
    });

const allVocab = [...vocab].map(display);
const common = allVocab.slice(0, COMMON_SIZE);

const output = `// generated by scripts/build-bigrams.mjs — do not edit by hand
// data: Peter Norvig's word and bigram counts (https://norvig.com/ngrams/),
// derived from the Google Web Trillion Word Corpus
export const GENERATED_BIGRAMS: Readonly<
    Partial<Record<string, readonly string[]>>
> = {
${entries.join("\n")}
};

export const GENERATED_COMMON: readonly string[] = ${JSON.stringify(common)};

// the full vocabulary in descending frequency order, for prefix completion
export const GENERATED_VOCAB: readonly string[] = ${JSON.stringify(allVocab)};
`;

const outputPath = join(
    dirname(fileURLToPath(import.meta.url)),
    "../src/prediction/bigrams.generated.ts",
);
writeFileSync(outputPath, output);
console.warn(
    `wrote ${entries.length} entries (${Math.round(output.length / 1024)} KB) to ${outputPath}`,
);
